substitutions:
  _COMPOSER_ENV_NAME: 'animepetcomposer'
  _LOCATION: 'us-central1'

steps:

  - name: gcr.io/cloud-builders/gcloud
    args: ['composer', 'environments', 'delete', '$_COMPOSER_ENV_NAME', '--location', 
           '$_LOCATION', '--quiet']